dist: xenial
sudo: required
language: python
python: 3.7
cache: pip
install: pip install -r app/requirements.txt
before_script: cd app
script:
    - python -m pytest
    - cd ..
    - docker build -t vd2org/challenge .
env:
  - BOTO_CONFIG=/dev/null
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push vd2org/challenge;
    fi